name: tf_gpu
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2019.3.9=hecc5488_0
  - certifi=2018.8.24=py35_1001
  - openssl=1.0.2r=h14c3975_0
  - patsy=0.5.1=py_0
  - seaborn=0.9.0=py_0
  - statsmodels=0.9.0=py35_0
  - _tflow_select=2.1.0=gpu
  - absl-py=0.4.1=py35_0
  - astor=0.7.1=py35_0
  - backcall=0.1.0=py35_0
  - blas=1.0=mkl
  - cudatoolkit=9.2=0
  - cudnn=7.2.1=cuda9.2_0
  - cupti=9.2.148=0
  - cycler=0.10.0=py35hc4d5149_0
  - dbus=1.13.2=h714fa37_1
  - decorator=4.3.0=py35_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - gast=0.2.0=py35_0
  - glib=2.56.2=hd408876_0
  - grpcio=1.12.1=py35hdbcaa40_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2019.1=144
  - ipykernel=4.10.0=py35_0
  - ipython=6.5.0=py35_0
  - ipython_genutils=0.2.0=py35hc9e07d0_0
  - jedi=0.12.1=py35_0
  - jinja2=2.10=py35_0
  - jpeg=9b=h024ee3a_2
  - jupyter_client=5.2.3=py35_0
  - jupyter_core=4.4.0=py35_0
  - kiwisolver=1.0.1=py35hf484d3e_0
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.36=hbc83047_0
  - libprotobuf=3.6.0=hdbcaa40_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.8=h26e45fe_1
  - markdown=2.6.11=py35_0
  - markupsafe=1.0=py35h14c3975_1
  - matplotlib=3.0.0=py35h5429711_0
  - mkl=2018.0.3=1
  - mkl_fft=1.0.6=py35h7dd41cf_0
  - mkl_random=1.0.1=py35h4414c95_1
  - ncurses=6.1=he6710b0_1
  - numpy=1.15.2=py35h1d66e8a_0
  - numpy-base=1.15.2=py35h81de0dd_0
  - pandas=0.23.4=py35h04863e7_0
  - parso=0.3.1=py35_0
  - pcre=8.42=h439df22_0
  - pexpect=4.6.0=py35_0
  - pickleshare=0.7.4=py35hd57304d_0
  - pip=10.0.1=py35_0
  - prompt_toolkit=1.0.15=py35hc09de7a_0
  - protobuf=3.6.0=py35hf484d3e_0
  - ptyprocess=0.6.0=py35_0
  - pygments=2.2.0=py35h0f41973_0
  - pyparsing=2.2.1=py35_0
  - pyqt=5.9.2=py35h05f1152_2
  - python=3.5.6=hc3d631a_0
  - python-dateutil=2.7.3=py35_0
  - pytz=2018.5=py35_0
  - pyzmq=17.1.2=py35h14c3975_0
  - qt=5.9.6=h8703b6f_2
  - readline=7.0=h7b6447c_5
  - scipy=1.1.0=py35hfa4b5c9_1
  - setuptools=40.2.0=py35_0
  - simplegeneric=0.8.1=py35_2
  - sip=4.19.8=py35hf484d3e_0
  - six=1.11.0=py35_1
  - sqlite=3.26.0=h7b6447c_0
  - tensorboard=1.10.0=py35hf484d3e_0
  - tensorflow=1.10.0=gpu_py35hd9c640d_0
  - tensorflow-base=1.10.0=gpu_py35had579c0_0
  - tensorflow-gpu=1.10.0=hf154084_0
  - termcolor=1.1.0=py35_1
  - tk=8.6.8=hbc83047_0
  - tornado=5.1.1=py35h7b6447c_0
  - traitlets=4.3.2=py35ha522a97_0
  - wcwidth=0.1.7=py35hcd08066_0
  - werkzeug=0.14.1=py35_0
  - wheel=0.31.1=py35_0
  - xarray=0.10.8=py35_0
  - xz=5.2.4=h14c3975_4
  - zeromq=4.2.5=hf484d3e_1
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - cftime==1.0.3.4
    - netcdf4==1.4.2
    - numexpr==2.6.9
    - scikit-learn==0.20.2
    - tables==3.4.4
    - liac-arff==2.4.0

